### ISSUE TITLE
error with the branches

### ISSUE THREAD

**Issue by 0xOnyx** [AngeTenShi/Inception#1]
Hi there,

I wanted to bring to your attention an error with the branches. Could you please take a look and make the necessary corrections?

Thank you for your attention to this matter.

Best regards, 
ONYX

**Comment by AngeTenShi** [comment]
Thanks it's fixed

**Comment by 0xOnyx** [comment]
Hi,

I am following up regarding the issue with the branches that I brought to your attention earlier. Unfortunately, it seems that the issue has still not been resolved.

Could you please provide me with an update on the status of the correction and an estimated timeline for when it will be resolved? I appreciate your prompt attention to this matter.

Thank you.

Best regards,
onyx
